export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function exportToCsv(data: Record<string, unknown>[], filename: string) {
  if (!data.length) return
  const headers = Object.keys(data[0])
  const rows = data.map((row) =>
    headers.map((h) => JSON.stringify(row[h] ?? '')).join(',')
  )
  const csv = [headers.join(','), ...rows].join('\n')
  downloadFile(csv, `${filename}.csv`, 'text/csv')
}

export function exportToJson(data: unknown, filename: string) {
  downloadFile(JSON.stringify(data, null, 2), `${filename}.json`, 'application/json')
}

export function printReport(title: string) {
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(`
    <html><head><title>${title}</title>
    <style>body{font-family:sans-serif;padding:2rem}h1{color:#4F46E5}</style>
    </head><body><h1>${title}</h1><p>Generated by EduPredict on ${new Date().toLocaleString()}</p></body></html>
  `)
  win.document.close()
  win.print()
}
